---
- name: Create new LXC container in Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

    vmid: 158
    api_user: "root@pam"
    api_password: "c0ff33"
    api_host: "192.168.1.150"
    container_password: "c0ff33"
    container_hostname: "ansible-lxc"
    proxmox_node: "dragon"
    ostemplate: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
    storage: "local"
    disk: "8"
    memory: 512
    nameserver: "192.168.1.254"
    cpus: 1
    cpuunits: 1024
    netif: 'net0=name=eth0,ip=192.168.1.158/24,gw=192.168.1.254,ip6=dhcp,bridge=vmbr0'

  tasks:
    - name: Debug environment to verify variables
      command: env
      register: env_out

    - debug:
        var: env_out.stdout_lines

    - name: Create LXC Container
      community.general.proxmox:
        vmid: "{{ vmid }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        password: "{{ container_password }}"
        hostname: "{{ container_hostname }}"
        node: "{{ proxmox_node }}"
        ostemplate: "{{ ostemplate }}"
        storage: "{{ storage }}"
        disk: "{{ disk }}"
        memory: "{{ memory }}"
        cores: 1
        cpus: "{{ cpus }}"
        cpuunits: "{{ cpuunits }}"
        nameserver: "{{ nameserver }}"
        netif: "{{ netif }}"  # make sure this is a string, not a dict
        unprivileged: true
        state: present
        validate_certs: false

