---
- name: Create new LXC container in Proxmox
  hosts: all
  tasks:
    - name: 'Create LXC Container'
      proxmox:
          vmid: '300' # Specifying Container ID
          api_user: root # Proxmox user
          api_password: c0ff33 # Password in plaintext !!!
          api_host: 192.168.1.150 # Proxmox hostname
          password: 'c0ff33' # Password in plaintext !!!
          hostname: 'ansible-lxc' # Container hostname
          node: 'dragon' # Name of Proxmox host
          cores: '1'
          cpus: '1'
          cpuunits: '1000'
          ostemplate: 'local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst' # Or use local:vztmpl/...
          storage: 'local' # Or use 'local'
          disk: '8'
          memory: '512'
          nameserver: '192.168.1.254'
          netif: '{"net0":"name=eth0,ip=192.168.1.157/24,gw=192.168.1.254,ip6=dhcp,bridge=vmbr0"}'
          state: 'present'
