---
- name: Create new LXC container in Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/proxmox.yml

  tasks:
    - name: Debug environment to verify variables
      command: "env"
      register: env_out

    - debug:
        var: env_out.stdout_lines

    - name: Create LXC Container
      proxmox:
        vmid: "{{ vmid }}"
        api_user: "root@pam"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        password: "{{ container_password }}"
        hostname: "{{ container_hostname }}"
        node: "{{ proxmox_node }}"
        ostemplate: "{{ ostemplate }}"
        storage: "{{ storage }}"
        disk: "{{ disk }}"
        memory: "{{ memory }}"      
        cores: 1
        netif: "{{ netif | from_yaml }}"
        unprivileged: true
        state: 'present'
        #cpus: "{{ container_cpus }}"
        #cpuunits: "{{ container_cpuunits }}"
        #nameserver: "{{ nameserver }}"     

