---
- name: Create new LXC container in Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

    # Proxmox API credentials
    api_host:       "192.168.1.150"
    api_user:       "root@pam"
    api_password:   "c0ff33"

    # Container settings
    proxmox_node:       "dragon"
    container_hostname: "ansible"
    container_password: "c0ff33"
    ostemplate:         "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"

    # LXC‐enabled storage
    storage:    "local-lvm"
    disk:       8       # GB
    memory:     512     # MB
    cpus:       1
    cpuunits:   1024
    nameserver: "192.168.1.254"
    vmid:       161

    # IP range
    network_prefix: "192.168.1"
    start_octet:    156
    end_octet:      165

  tasks:
    - name: Generate octet list {{ start_octet }}–{{ end_octet }}
      ansible.builtin.set_fact:
        candidate_octets: "{{ lookup('ansible.builtin.sequence',
                                      'start=' ~ start_octet ~ ' end=' ~ end_octet,
                                      wantlist=True) }}"

    - name: Build candidate IPs
      ansible.builtin.set_fact:
        candidate_ips: "{{ candidate_octets
                          | map('string')
                          | map('regex_replace','^(.*)$', network_prefix ~ '.\\1')
                          | list }}"

    - name: Ping each candidate to find a free IP
      become: true                                # run as root so ping can open raw sockets
      ansible.builtin.command:
        cmd: "timeout 1 ping -c1 -W1 {{ item }}"
      register: ping_results
      failed_when: false
      changed_when: false
      loop: "{{ candidate_ips }}"
      loop_control:
        label: "{{ item }}"

    - name: Pick the first non-responding IP (rc == 1)
      ansible.builtin.set_fact:
        free_ip: "{{ item.item }}"
      loop: "{{ ping_results.results }}"
      when:
        - item.rc == 1      # host unreachable is the only “free” case
        - free_ip is not defined
      run_once: true

    - name: Debug chosen free_ip
      ansible.builtin.debug:
        var: free_ip

    - name: Create LXC Container
      community.general.proxmox:
        api_host:       "{{ api_host }}"
        api_user:       "{{ api_user }}"
        api_password:   "{{ api_password }}"
        node:           "{{ proxmox_node }}"
        vmid:           "{{ vmid }}"
        hostname:       "{{ container_hostname }}"
        ostemplate:     "{{ ostemplate }}"
        storage:        "{{ storage }}"
        disk:           "{{ disk }}"
        memory:         "{{ memory }}"
        cpus:           "{{ cpus }}"
        cpuunits:       "{{ cpuunits }}"
        nameserver:     "{{ nameserver }}"
        password:       "{{ container_password }}"
        netif:
          net0: "name=eth0,bridge=vmbr0,ip={{ free_ip }}/24,gw={{ nameserver }},ip6=dhcp"
        unprivileged:   true
        state:          present
        validate_certs: false
      no_log: true
