---
- name: Create new LXC container in Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    api_host: "192.168.1.150"
    api_user: "root@pam"
    api_password: "c0ff33"
    container_password: "c0ff33"
    container_hostname: "ansible"
    proxmox_node: "dragon"
    ostemplate: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst"
    storage: "local"
    disk: "8"
    memory: 512
    cpus: 1
    cpuunits: 1024
    nameserver: "192.168.1.254"
    vmid: 160
    netif: "net0=name=eth0,bridge=vmbr0,ip=192.168.1.160/24,gw=192.168.1.254,ip6=dhcp"

  tasks:
    - name: Force netif as a string
      set_fact:
        netif: "net0=name=eth0,bridge=vmbr0,ip=192.168.1.160/24,gw=192.168.1.254,ip6=dhcp"
 
    - name: Create LXC Container
      community.general.proxmox:
        vmid: "{{ vmid }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        password: "{{ container_password }}"
        hostname: "{{ container_hostname }}"
        node: "{{ proxmox_node }}"
        ostemplate: "{{ ostemplate }}"
        storage: "{{ storage }}"
        disk: "{{ disk }}"
        memory: "{{ memory }}"
        cpus: "{{ cpus }}"
        cpuunits: "{{ cpuunits }}"
        nameserver: "{{ nameserver }}"
        netif: "{{ netif | string }}"
        unprivileged: true
        state: present
        validate_certs: false

