---
- name: Debug effective HOME and remote_tmp
  command: "env"
  register: env_out

- debug:
    var: env_out.stdout_lines


- name: Create new LXC container in Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/proxmox.yml

  tasks:
    - name: Create LXC Container
      proxmox:
        vmid: "{{ vmid }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        password: "{{ container_password }}"
        hostname: "{{ container_hostname }}"
        node: "{{ proxmox_node }}"
        cores: "{{ container_cores }}"
        cpus: "{{ container_cpus }}"
        cpuunits: "{{ container_cpuunits }}"
        ostemplate: "{{ ostemplate }}"
        storage: "{{ storage }}"
        disk: "{{ disk }}"
        memory: "{{ memory }}"
        nameserver: "{{ nameserver }}"
        netif: "{{ netif }}"
        state: 'present'
